In [1]:
import pandas as pd

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [3]:
df=pd.read_csv('Concatenated_Data.csv')

In [4]:
df

,Unnamed: 0,Fiscal Year,Major,Sex,Institution Name,Award Level Code,Race and Ethnicity,Awards/Degrees Conferred
0,0,2023,03.01 - Natural Resources Conservation and Res...,Female,Antioch University-New England,Doctor's degree - research/scholarship,Asian,1
1,1,2023,03.01 - Natural Resources Conservation and Res...,Female,Antioch University-New England,Doctor's degree - research/scholarship,White,4
2,2,2023,03.01 - Natural Resources Conservation and Res...,Female,Arizona State University Campus Immersion,Doctor's degree - research/scholarship,Hispanic or Latino,1
3,3,2023,03.01 - Natural Resources Conservation and Res...,Female,Arizona State University Campus Immersion,Doctor's degree - research/scholarship,White,3
4,4,2023,03.01 - Natural Resources Conservation and Res...,Female,Ball State University,Doctor's degree - research/scholarship,White,1
...,...,...,...,...,...,...,...,...
13866,1120,2021,16.0905 - Spanish Language and Literature.,Female,Washington University in St Louis,Doctor's degree - research/scholarship,Hispanic or Latino,1
13867,1121,2021,16.0901 - French Language and Literature.,Male,Washington University in St Louis,Doctor's degree - research/scholarship,White,1
13868,1122,2021,"27.0301 - Applied Mathematics, General.",Male,Yale University,Doctor's degree - research/scholarship,White,1
13869,1123,2021,"50.0703 - Art History, Criticism and Conservat...",Female,Yale University,Doctor's degree - research/scholarship,White,1
13870,1124,2021,"50.0703 - Art History, Criticism and Conservat...",Male,Yale University,Doctor's degree - research/scholarship,White,2

In [18]:
excluded_colleges = [
    "American College of Technology",
    "American College of Education",
    "American Military University",
    "American Public University System",
    "American Sentinel University",
    "Ashworth College",
    "Aspen University",
    "California InterContinental University",
    "California Southern University",
    "Capella University",
    "Everest College",
    "Everest Institute",
    "London School of Business and Finance",
    "National Institute of Technology",
    "National Paralegal College",
    "National University College",
    "Neumont University",
    "New England College of Business and Finance",
    "New Charter University",
    "NewSchool of Architecture and Design",
    "Northwestern College",
    "Ohio Business College",
    "Olympia Career Training Institute",
    "Pacific College of Health and Science",
    "Parks College",
    "Pennco Tech",
    "Pima Medical Institute",
    "Pinnacle Career Institute",
    "Pioneer Pacific College",
    "Platt College",
    "Plaza College",
    "Porter and Chester Institute",
    "Post University",
    "Potomac College",
    "Provo College",
    "Rasmussen College",
    "Rocky Mountain College of Art and Design",
    "Rocky Mountain University of Health Professions",
    "Rocky Vista University College of Osteopathic Medicine",
    "SAE Institute",
    "Salem International University",
    "San Joaquin Valley College",
    "Schiller International University",
    "School of Visual Arts",
    "Seacoast Career Schools",
    "Setanta College",
    "South College",
    "South University",
    "Southern Careers Institute",
    "Southern States University",
    "Southwestern College",
    "Spartan College of Aeronautics and Technology",
    "Specs Howard School of Media Arts",
    "Strayer University",
    "Sullivan University",
    "Suncoast College of Health",
    "UEI College",
    "United States University",
    "Universal Technical Institute",
    "University of Advancing Technology",
    "University of Atlanta",
    "University of Liverpool",
    "University of Phoenix",
    "University of the Potomac",
    "U.S. Career Institute",
    "Walden University",
    "West Coast University",
    "Western State College of Law",
    "Western State University College of Law",
    "WyoTech (Wyoming Technical Institute)"
]


filtered_df = df[~df['Institution Name'].isin(excluded_colleges)]

df_combined.to_csv("filtered_data.csv", index=False)

In [19]:
df2= pd.read_csv('/Users/dennisespejo/Desktop/ncses_table_raw_data_IPEDS_C_2025-06-24T17_40_36Z.csv')

In [20]:
df2

,Fiscal Year,CIP Code and Description (4 digit),Award Level Code,Sex,Race and Ethnicity,Institution Name,Awards/Degrees Conferred
0,2023,"04.08 - Architectural History, Criticism, and ...",Doctor's degree - research/scholarship,Female,Hispanic or Latino,Cornell University,1
1,2023,"04.08 - Architectural History, Criticism, and ...",Doctor's degree - research/scholarship,Male,White,Cornell University,1
2,2023,40.05 - Chemistry.,Doctor's degree - research/scholarship,Female,Hispanic or Latino,California Institute of Technology,1
3,2023,40.05 - Chemistry.,Doctor's degree - research/scholarship,Female,Hispanic or Latino,Case Western Reserve University,1
4,2023,40.05 - Chemistry.,Doctor's degree - research/scholarship,Female,Hispanic or Latino,Colorado State University-Fort Collins,1
...,...,...,...,...,...,...,...
13864,2008,40.05 - Chemistry.,Doctor's degree - research/scholarship,Male,Temporary visa holder,University of Wisconsin-Madison,8
13865,2008,40.05 - Chemistry.,Doctor's degree - research/scholarship,Male,Temporary visa holder,University of Wisconsin-Milwaukee,3
13866,2008,40.05 - Chemistry.,Doctor's degree - research/scholarship,Male,Temporary visa holder,University of Wyoming,1
13867,2008,40.05 - Chemistry.,Doctor's degree - research/scholarship,Male,Temporary visa holder,Virginia Polytechnic Institute and State Unive...,9
13868,2008,40.05 - Chemistry.,Doctor's degree - research/scholarship,Male,Temporary visa holder,Western Michigan University,3

In [21]:
new_order= ['Fiscal Year','CIP Code and Description (4 digit)','Sex','Institution Name','Award Level Code','Race and Ethnicity', 'Awards/Degrees Conferred']

In [22]:
df2=df2[new_order]

In [23]:
df2

,Fiscal Year,CIP Code and Description (4 digit),Sex,Institution Name,Award Level Code,Race and Ethnicity,Awards/Degrees Conferred
0,2023,"04.08 - Architectural History, Criticism, and ...",Female,Cornell University,Doctor's degree - research/scholarship,Hispanic or Latino,1
1,2023,"04.08 - Architectural History, Criticism, and ...",Male,Cornell University,Doctor's degree - research/scholarship,White,1
2,2023,40.05 - Chemistry.,Female,California Institute of Technology,Doctor's degree - research/scholarship,Hispanic or Latino,1
3,2023,40.05 - Chemistry.,Female,Case Western Reserve University,Doctor's degree - research/scholarship,Hispanic or Latino,1
4,2023,40.05 - Chemistry.,Female,Colorado State University-Fort Collins,Doctor's degree - research/scholarship,Hispanic or Latino,1
...,...,...,...,...,...,...,...
13864,2008,40.05 - Chemistry.,Male,University of Wisconsin-Madison,Doctor's degree - research/scholarship,Temporary visa holder,8
13865,2008,40.05 - Chemistry.,Male,University of Wisconsin-Milwaukee,Doctor's degree - research/scholarship,Temporary visa holder,3
13866,2008,40.05 - Chemistry.,Male,University of Wyoming,Doctor's degree - research/scholarship,Temporary visa holder,1
13867,2008,40.05 - Chemistry.,Male,Virginia Polytechnic Institute and State Unive...,Doctor's degree - research/scholarship,Temporary visa holder,9
13868,2008,40.05 - Chemistry.,Male,Western Michigan University,Doctor's degree - research/scholarship,Temporary visa holder,3

In [24]:
df2=df2.rename(columns={'CIP Code and Description (4 digit)':'Major'})

In [25]:
df_combined=pd.concat([df2,filtered_df])

In [26]:
df_combined

,Fiscal Year,Major,Sex,Institution Name,Award Level Code,Race and Ethnicity,Awards/Degrees Conferred,Unnamed: 0
0,2023,"04.08 - Architectural History, Criticism, and ...",Female,Cornell University,Doctor's degree - research/scholarship,Hispanic or Latino,1,NaN
1,2023,"04.08 - Architectural History, Criticism, and ...",Male,Cornell University,Doctor's degree - research/scholarship,White,1,NaN
2,2023,40.05 - Chemistry.,Female,California Institute of Technology,Doctor's degree - research/scholarship,Hispanic or Latino,1,NaN
3,2023,40.05 - Chemistry.,Female,Case Western Reserve University,Doctor's degree - research/scholarship,Hispanic or Latino,1,NaN
4,2023,40.05 - Chemistry.,Female,Colorado State University-Fort Collins,Doctor's degree - research/scholarship,Hispanic or Latino,1,NaN
...,...,...,...,...,...,...,...,...
13866,2021,16.0905 - Spanish Language and Literature.,Female,Washington University in St Louis,Doctor's degree - research/scholarship,Hispanic or Latino,1,1120.0
13867,2021,16.0901 - French Language and Literature.,Male,Washington University in St Louis,Doctor's degree - research/scholarship,White,1,1121.0
13868,2021,"27.0301 - Applied Mathematics, General.",Male,Yale University,Doctor's degree - research/scholarship,White,1,1122.0
13869,2021,"50.0703 - Art History, Criticism and Conservat...",Female,Yale University,Doctor's degree - research/scholarship,White,1,1123.0
13870,2021,"50.0703 - Art History, Criticism and Conservat...",Male,Yale University,Doctor's degree - research/scholarship,White,2,1124.0